### ISSUE TITLE
GPU overloads when sample number exceeds 5 thousand

### ISSUE THREAD

**Issue by ilikeit5265** [lilanpei/NMT#1]
using the model.fit_generator() function with around over 5k samples. will crash google colaboratory

**Comment by lilanpei** [comment]
Yes, to reduce the consumption of memory, you can consider reducing the vocabulary size, truncating the sentences with a smaller max-length, using a smaller embedding-size and a smaller batch-size.

**Comment by ilikeit5265** [comment]
Wouldn't that decrease the model's accuracy?

**Comment by ilikeit5265** [comment]
I'm actually trying to use a pre-built model from GitHub and train it on a grapheme-to-phoneme dataset; since it is unnecessary, how would I go about removing the implemented FastText word2vec embedding?

**Comment by ilikeit5265** [comment]
I am using this model because it is the only functional bidirectional model that uses beam decoding that I could find.

**Comment by lilanpei** [comment]
T think you can use the one-hot representation instead of the word-embedding.
