### ISSUE TITLE
The pre-trained embedding matrix found in the example code is missing

### ISSUE THREAD

**Issue by ilikeit5265** [lilanpei/NMT#2]
I wanted to run the "NMT - Microblog - ZH to EN - Bi-GRU + Attention +  Fasttext word embedding + k-Beam search + BLEU score.ipynb" file in my colaboratory but couldn't find the pre-trained embedding matrix

**Comment by lilanpei** [comment]
Hi, in the new update, I add a function called "download_fasttext_word_embedding()" which you can use to download the pre-trained embedding matrix. But consider the RAM colab offered for free use, it's impossible to load the matrix into the memory, so I suggest to use the files I uploaded  named "input_emb_matrix_Microblog.npy" and "output_emb_matrix_Microblog.npy" for the customized the embedding vectors mapped from the downloaded pre-trained embedding matrix.

**Comment by ilikeit5265** [comment]
Thanks a lot, it worked.
